version: "3"
services:
  install:
    image: node:14
    working_dir: /app
    command: "yarn install"
    volumes:
      - ./:/app
      - /app/.git

  build:
    image: node:14
    working_dir: /app
    command: "yarn build"
    volumes:
      - ./:/app
      - /app/.git

  start:
    image: node:14
    working_dir: /app
    command: "yarn start"
    ports:
      - 1234:1234
      - 12345:12345
    volumes:
      - ./:/app
      - /app/.git
