version: '3'
services:
  install:
    image: node:12
    working_dir: /app
    command: 'yarn install --silent --frozen-lockfile'
    volumes:
      - ./:/app
      - /app/.git

  build:
    image: node:12
    working_dir: /app
    command: 'yarn run build'
    volumes:
      - ./:/app
      - /app/.git

  start:
    image: node:12
    working_dir: /app
    command: 'yarn start'
    ports:
      - 1234:1234
    volumes:
      - ./:/app
      - /app/.git
